version: '3.7'

services:  
  db:
    image: mysql:latest # use latest version of mysql
    container_name: db # add a name for the container
    build: 
      context: ./ # use the current directory as the context
      dockerfile: dockerfile/mysql # use the Dockerfile in the current directory
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: wibuslayer
      MYSQL_ROOT_PASSWORD: hieudai1998
      MYSQL_PASSWORD: hieudai1998
      MYSQL_DATABASE: pet_project # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'

volumes: # add persistent data even if container is removed.
  my-db:
    driver: local